/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TaskApp;


import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import controller.ProjectController;
import controller.TaskController;
import model.Project;
import model.Task;
import util.ConnectionFactory;
import view.MainScreen;

public class App {

    public static void main(String[] args){
           
           // Testando Task Controller:
           /*
           TaskController taskController = new TaskController();
           Task task = new Task();
         
         
           task.setName("Minha Primeira Tarefa");
           task.setId(23);
           task.setIdProject(10);
           task.setDescription("update da minha primeira tarefa");
           task.setIsCompleted(true);
           task.setDeadline(new Date());
           // taskController.update(task);
           // taskController.save(task);
           // taskController.removeById(2);
           taskController.update(task);
           List<Task> tasks = taskController.getAll(1);
           System.out.println("Total de projetos no banco de dados: " + tasks.size());
           */
           
           MainScreen mainscreen = new MainScreen();
           mainscreen.setVisible(true);
         
    }
}
